sudo: required
language:
  - node_js
services:
  - docker

before_install:
  - docker build -t unhang/docker-react -f Dockerfile.dev .

script:
  - docker run unhang/docker-react npm run test -- --coverage
 